### ISSUE TITLE
"stdin" possibility?

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#40]
Would it be possible to have a "stdin"? That could be set via async function or buffer / string input etc... ? I seen the process is set to undefined. But I would assume it could be done. This would introduce possibility for REPL in future (if we can store / persist variables.)

**Comment by sebastianwessel** [comment]
see #39

I don't think, stuff like stdin, will make it into this lib.

**Comment by MarketingPip** [comment]
@sebastianwessel - I know [Pyodide](https://pyodide.org/) has a way to execute async / inputs by blocking process inside web assembly. 

See [here](https://pyodide.org/en/stable/usage/streams.html) - if this helps. (if I am just being a bug and not a help too - please do tell me to f* off kindly lol). Just trying to help with anything I can reference.

**Comment by sebastianwessel** [comment]
There is a difference between async and stream. Async operations are supported - like the fetch adapter.
Here, the guest system is pausing, which gives the host system the option to run host-side-code. When the host async is fulfilled, the result value is written to the webessambly memory, as well as the status of the async. The host needs to explicit call the quickjs to check the async status. The quickjs "sees", that the async is fulfilled, and the result value is available. Now the quickjs can resume the job and the host system is again in a kind of "wait until quickjs completes".

A stream is working differently. Working with streams means, the host gets data from the OS, the data must be written to the webassembly memory and the webassembly (in our case quickjs) must read the value from the memory.

There, you would need to have something like this:

- quickjs event loop tick
- host event loop tick -> read from stdin and copy value to webassambly memory
- quickjs event loop tick -> read from webassambly memory and push value to client side stream
- host event loop tick -> read from stdin and copy value to webassambly memory
- quickjs event loop tick -> read from webassambly memory and push value to client side stream
- host event loop tick -> read from stdin and copy value to webassambly memory
- quickjs event loop tick -> read from webassambly memory and push value to client side stream

As quickjs does not have an event loop, things like streams, time functions (setTimeout, setInterval) do not work correctly.

The only way to get it somehow working is, to wrap the reading of stdin into some custom async host function, which can be called by the quickjs side.

Something like this:

```ts
import * as readline from 'readline';

async function readFromStdin(): Promise<string> {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    return new Promise((resolve) => {
        rl.question('Enter some input: ', (input: string) => {
            resolve(input);
            rl.close();
        });
    });
}

(async () => {
    const input = await readFromStdin();
    console.log('You entered:', input);
})();
```

This is a possible workaround I guess (did not try it out), but you will lose any benefits of streams and the client code needs to be adjustes, to use a async function instead of the stream.

**Comment by MarketingPip** [comment]
@sebastianwessel - hey man, just playing around. This works for 'stdin' etc... : 

```js
   console: {
      log: (...message) => {
    if (typeof message[0] === 'object' && message[0] !== null && message[0].hasOwnProperty('readline')) {
      const input = prompt(message)
      return input
    } else {
      outputCallback(message);
    }
  },
```

which if this was ASYNC etc... ;) we could attach a console.read  etc and easily add stdin. Just a thought ;)
