### ISSUE TITLE
Apply Babel Transformations 

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#46]
I think it would be ideal to have a preset babel config that does following:

- Convert's any .then() etc into promises, setTimeOut() etc... (to ensure all code is awaited)
- Loop protection (add breaks if loop is detected). 
- Convert require to import.

Some things that might be useful -

[tripwire](https://github.com/tjanczuk/tripwire) - breaks EVENT LOOP in C - useful... 
https://www.npmjs.com/package/loop-breaker?activeTab=readme
https://codepen.io/jcubic/pen/yLKGWLa
https://meta.stackoverflow.com/a/361084
https://github.com/mattdesl/babel-plugin-import-to-require
https://www.npmjs.com/package/vite-plugin-require-transform?activeTab=code

As well tons of existing babel plugins.

Possibly a flag option would be suitable for this, or a plugin?

**Comment by sebastianwessel** [comment]
Sorry, no. There is no way something like this will make it into this lib.
It is up to the developer/user to provide code, which is functional and fits the requirements and restrictions.

**Comment by sebastianwessel** [comment]
Sorry, no. There is no way something like this will make it into this lib.
It is up to the developer/user to provide code, which is functional and fits the requirements and restrictions.

**Comment by MarketingPip** [comment]
@sebastianwessel - again hence I suggested it as library. Think about when using this in browser. As well look at the tripwire regardless...

**Comment by sebastianwessel** [comment]
Again.
QuickJS is not Node.js, and there is no event loop like in Node.js, which means, even if this native c code from tripwire can be somehow compiled and integrated into the webassembly, it simply can not work. No loop = no way to stop the loop.

As mentioned before, this lib is focusing on executing a given source code.
If the code is generated by AI or whatever, it is fine to have some cleanup/convert step, but not as part of the runtime/this lib.
It must be done before on the host side, and should be a plugin or similar of the AI generation step, rather than a step in the execution part.

**Comment by MarketingPip** [comment]
@sebastianwessel - fair enough! Wanted to throw some ideas etc. (Figured maybe a loop blocker etc might be good - considering typescript can be compiled etc... )

That said you might wanna peak [here](https://github.com/ctn-malone/qjs-ext-lib/tree/master) - see if you can steal anything out of it. Cheers 👍

**Comment by sebastianwessel** [comment]
In the upcoming release, typescript is supported. Transpile only - so no type checking (similar to bun)
